### PR TITLE
Display uploaded files and allow them to be removed

### PR DESCRIPTION
**Pull request by annalinneajohansson**

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-3qfy5er Feedback filuppladdning formulär](https://app.clickup.com/t/3qfy5er)

**Comment by annalinneajohansson** [comment]
Not quite sure why git are detecting all of the content as changed i fields.js, but my actual changes are made within the fileInputOnChange() method

**Comment by annalinneajohansson** [comment]
https://github.com/helsingborg-stad/styleguide/pull/595/commits/9102654b7e0050ec47abefbbe73642aecb20efd2

**Comment by NiclasNorin** [comment]
Moved to https://github.com/helsingborg-stad/styleguide/pull/603

**Pull request closed without merging**
